import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { User } from '../../users/entities/user.entity';

export enum FileKind {
  /** Creator portfolio image: public, shown in the Applicants content strip. */
  PORTFOLIO = 'portfolio',
  /** Insights screenshot for stats verification: owner and admins only. */
  VERIFICATION = 'verification',
}

/** An uploaded image. The bytes live in StorageService under `storageKey`. */
@Entity('files')
@Index(['ownerId', 'kind'])
export class StoredFile {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'uuid' })
  ownerId: string;

  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'ownerId' })
  owner: User;

  @Column({ type: 'enum', enum: FileKind })
  kind: FileKind;

  /** Detected from the file's bytes, never from the client's header. */
  @Column({ type: 'varchar', length: 32 })
  mimeType: string;

  @Column({ type: 'int' })
  size: number;

  /** Generated by the server; never derived from the uploaded file name. */
  @Column({ type: 'varchar', length: 64, unique: true })
  storageKey: string;

  /** Order in the portfolio; null for other kinds. */
  @Column({ type: 'int', nullable: true })
  position: number | null;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date;
}
